name: Deploy API EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Configurar Java 21
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # 3️⃣ Build Maven
      - name: Build API
        run: mvn clean package -DskipTests

      # 4️⃣ Configurar SSH
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_KEY }}

      # 5️⃣ Deploy para EC2 via nohup e copiar api.p12
      - name: Deploy to EC2
        run: |
          JAR_LOCAL=target/lumilivre-0.0.1-PROD.jar
          JAR_REMOTE=/home/ec2-user/api/lumilivre-0.0.1-PROD.jar
          BACKUP_REMOTE=/home/ec2-user/api/lumilivre-0.0.1-PROD-backup.jar
          KEYSTORE_LOCAL=api.p12
          HOST=ec2-user@100.27.206.216

          # Copiar .jar e keystore para EC2
          scp -o StrictHostKeyChecking=no $JAR_LOCAL $HOST:/home/ec2-user/
          scp -o StrictHostKeyChecking=no $KEYSTORE_LOCAL $HOST:/home/ec2-user/api/api.p12

          # Conectar na EC2 e atualizar API
          ssh -o StrictHostKeyChecking=no $HOST "\
            mkdir -p /home/ec2-user/api && \
            pkill -f 'lumilivre-0.0.1-PROD.jar' || true && \
            if [ -f $JAR_REMOTE ]; then mv $JAR_REMOTE $BACKUP_REMOTE; fi && \
            mv /home/ec2-user/lumilivre-0.0.1-PROD.jar $JAR_REMOTE && \
            chmod 600 /home/ec2-user/api/api.p12 && \
            chown ec2-user:ec2-user /home/ec2-user/api/api.p12 && \
            # Carregar variáveis do arquivo .env
            set -a && source /home/ec2-user/api/.env && set +a && \
            nohup java \
              -Dserver.ssl.key-store=/home/ec2-user/api/api.p12 \
              -Dserver.ssl.key-store-type=PKCS12 \
              -jar $JAR_REMOTE > /home/ec2-user/api/app.log 2>&1 & \
          "
